# Generated by Django 4.0.5 on 2022-06-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0002_rename_name_movielist_title_movielist_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='OttPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('about', models.CharField(max_length=50)),
                ('website', models.URLField(max_length=100)),
            ],
        ),
    ]
