# Generated by Django 4.0.5 on 2022-06-07 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0003_ottplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='platform',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='movielist', to='movielist.ottplatform'),
            preserve_default=False,
        ),
    ]
